config/routes.rb
Rails.application.routes.draw do
  root 'entries#index'

  resources :entries, only: [:index, :show]

  get 'admin' => 'admin/entries#index'
  namespace :admin do
    resources :entries, only: [:index, :new]
  end

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  USER_REQUEST = "https://api.github.com/users/#{ENV['GITHUB_USERNAME']}".freeze
  RAW_REQUEST = "https://raw.githubusercontent.com/#{ENV['GITHUB_USERNAME']}"
                .freeze

  # TODO: instead of destroy_all, figure out which entries were unstarred and
  # remove them. Or do some sort of pretty URL.
  # TODO: only add starred repos that the user owns
  def self.load_starred
    Entry.destroy_all
    response = RestClient.get "#{USER_REQUEST}/starred"
    upsert_entries(response)
  end

  def self.upsert_entries(response)
    parsed_response = JSON.parse(response)
    parsed_response.each do |entry|
      upsert(entry)
    end
  end

  def self.upsert(entry_hash)
    entry_json = JSON.generate(entry_hash)
    entry = find_or_initialize_by(name: entry_hash['name'])
    content = entry.generate_content
    if entry.id
      entry.update(github_response: entry_json, content: content)
    else
      entry.github_response = entry_json
      entry.content = content
      entry.save
    end
  end

  def generate_content
    entry_request = "#{RAW_REQUEST}/#{name}/natsyrk/portfolio_entry.md"
    RestClient.get(entry_request) do |response|
      return generate_backup_content unless response.code == 200
      response
    end
  end

  def generate_backup_content
    readme_request = "#{RAW_REQUEST}/#{name}/master/README.md"
    RestClient.get(readme_request) do |response|
      return nil unless response.code == 200
      response
    end
  end
end

app/controllers/admin/entries_controller.rb
class Admin::EntriesController < ApplicationController
  before_action :set_entries

  # GET /admin/entries
  def index
  end

  # GET /admin/entries/new
  def new
    Entry.load_starred
    respond_to do |format|
      format.js {}
      format.html { redirect_to admin_entries_path }
    end
  end

  private

  def set_entries
    @entries = Entry.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show]

  # GET /entries
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/entries/_entry.html.erb
<li><%= link_to entry.name, entry %></li>

app/views/admin/entries/index.html.erb
<%= link_to 'Update Entries From Github',
            new_admin_entry_path,
            remote: true,
            id: "update-entries" %>

<h1>Entries</h1>

<ul id="entries-list">
  <%= render @entries %>
</ul>

app/views/admin/entries/new.js.erb
$('#entries-list').html('<%= j render @entries %>');

app/views/entries/_entry.html.erb
<li><%= link_to entry.name, entry %></li>

app/views/entries/index.html.erb
<h1>Check out these awesome projects:</h1>

<ul>
  <%= render @entries %>
</ul>

app/views/entries/show.html.erb
<%= @entry.name %><br>
<%= @entry.content %>

<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Natsyrk</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to 'Admin', admin_path %><br>

<%= yield %>

</body>
</html>